site_name: dap.gal | SysAdmin
site_description: Administrador de sistemas especializado en ciberseguridad, virtualización e infraestrutura Linux.
site_author: David Álvarez Pampillón
site_url: https://dap.gal/
use_directory_urls: false
docs_dir: root
copyright: >-
  &copy; 2020-<script>document.write(new Date().getFullYear())</script> <a href="https://dap.gal" target="_blank" rel="noopener noreferrer" style="color:DDDDDD"><strong>dap</strong></a> | All rights reserved.

repo_name: davidalvarezp/dap.gal
repo_url: https://github.com/davidalvarezp/dap.gal
edit_uri: edit/main/docs/

theme:
 name: material
 language: es
 logo: assets/img/logo.webp
 favicon: assets/img/favicon.ico
 font:
  text: JetBrains Mono
 features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.top
  - navigation.sections
  - search.suggest
  - search.highlight
  - content.code.copy
  - content.code.annotate
 palette:
  scheme: default
  primary: black
  accent: green


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - tags
  - projects

# Extra
extra:
  scope: /
  generator: false
  social:
    - icon: simple/youtube
      link: https://youtube.com/@davidalvarezp
    - icon: simple/twitch
      link: https://twitch.tv/sudodap
    - icon: simple/telegram
      link: https://t.me/sudodap
    - icon: simple/x 
      link: https://x.com/sudodap
    - icon: simple/instagram
      link: https://instagram.com/davidalvarezzp
    - icon: simple/discord
      link: https://discord.gg/x7JFKT2n4X

  analytics:
    provider: google
    property: G-MXJTP7C62L
    feedback:
      title: Fue útil esta página?
      ratings:
        - icon: material/thumb-up-outline
          name: Si
          data: 1
          note: Gracias por el feedback!
        - icon: material/thumb-down-outline
          name: Non
          data: 0
          note: Gracias, seguiré mejorando.
  consent:
    #title: Uso de Cookies
    description: >- 
      Utilizamos cookies para mejorar tu experiencia en nuestro sitio web y analizar el tráfico de forma anónima. 
      Al continuar navegando, aceptas su uso. Puedes cambiar tus preferencias en cualquier momento.
    actions:
      - accept
      - manage
 
extra_css:
  - assets/css/extra.css

# Navegación
nav:
  - Inicio: index.md
  - Blog: /blog/
  - Manual de Linux: /man-linux/
  - Contacto: /contacto/