#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # Permitir tráfico local y conexiones ya establecidas
        ct state established,related accept
        iif "lo" accept

	# Permitir Prometheus
	tcp dport 9100 accept

        # Permitir SSH (opcional) y el puerto de WireGuard
        tcp dport 22 accept
        udp dport 51820 accept

        # Permitir ICMP (Ping)
        ip protocol icmp accept
    }

    chain forward {
        type filter hook forward priority 0; policy accept;
        # Permitir que el tráfico de la VPN (wg0) fluya
        iifname "wg0" accept
        oifname "wg0" accept
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100; policy accept;
        # Hacer NAT del tráfico que viene de la VPN hacia la interfaz del contenedor (eth0)
        oifname "eth0" masquerade
    }
}
