# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template: -d debian -r bookworm -a arm64
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Distribution configuration
lxc.include = /usr/share/lxc/config/common.conf
lxc.arch = linux64

# Container specific configuration
#! lxc.apparmor.profile = generated
#!lxc.apparmor.allow_nesting = 1
lxc.rootfs.path = dir:/var/lib/lxc/CI03-STATS/rootfs
lxc.uts.name = CI03-STATS

# Start config
lxc.start.auto = 1
lxc.start.order = 2
lxc.start.delay = 5

# System config
lxc.cgroup2.cpuset.cpus = 1
lxc.cgroup2.cpu.weight = 100
lxc.cgroup2.memory.max = 256M
lxc.cgroup2.memory.swap.max = 512M

# Network config
lxc.net.0.type = veth
lxc.net.0.link = br0
lxc.net.0.flags = up
lxc.net.0.ipv4.address = 192.168.1.13/24
lxc.net.0.ipv4.gateway = 192.168.1.1
