site_name: dap's Blog
site_description: Articulos, tutoriales y recursos sobre administración de sistemas, desarrollo y seguridad informática.
site_author: David Álvarez Pampillón
site_url: https://dap.gal/blog/
copyright: Copyright &copy; 2026 <a href="https://dap.gal" target="_blank" rel="noopener noreferrer" style="color:DDDDDD"><strong>dap</strong></a> | All rights reserved.

# Configuración del Repositorio
repo_name: dap.gal/blog
repo_url: https://github.com/davidalvarezp/dap.gal/tree/main/projects/blog
edit_uri: edit/main/docs/

# Configuración del Tema
theme:
 name: material
 language: es
 logo: /assets/img/logo.webp
 favicon: /assets/img/favicon.ico
 #font:
 # text: JetBrains Mono
 features:
   - navigation.tabs
   - navigation.tabs.sticky
   - navigation.sections
   - navigation.expand
   - navigation.path
   - navigation.top
   - navigation.indexes
   - navigation.tracking
   - navigation.footer
   - search.suggest
   - search.highlight
   - search.share
   - content.code.copy
   - content.code.annotate
   - content.tooltips
   #- header.autohide
   - toc.follow

 palette:
   # Selector de paleta para modo claro
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: black
     accent: green
     toggle:
       icon: material/toggle-switch
       name: Cambiar a modo oscuro
   # Selector de paleta para modo oscuro
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: black
     accent: green
     toggle:
       icon: material/toggle-switch-off-outline
       name: Cambiar a modo claro

# Extensiones Markdown
markdown_extensions:
 - admonition
 - attr_list
 - def_list
 - footnotes
 - md_in_html
 - toc:
     permalink: true
     toc_depth: 3
 - pymdownx.arithmatex:
     generic: true
 - pymdownx.betterem:
     smart_enable: all
 - pymdownx.caret
 - pymdownx.details
 - pymdownx.emoji:
     emoji_index: !!python/name:material.extensions.emoji.twemoji
     emoji_generator: !!python/name:material.extensions.emoji.to_svg
 - pymdownx.highlight:
     anchor_linenums: true
     line_spans: __span
     pygments_lang_class: true
 - pymdownx.inlinehilite
 - pymdownx.keys
 - pymdownx.magiclink:
     repo_url_shorthand: true
 - pymdownx.mark
 - pymdownx.smartsymbols
 - pymdownx.superfences:
     custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:pymdownx.superfences.fence_code_format
 - pymdownx.tabbed:
     alternate_style: true
 - pymdownx.tasklist:
     custom_checkbox: true
 - pymdownx.tilde

# Plugins
plugins:
  - search
  - blog:
      blog_dir: .
      authors_profiles: true
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

# Extra
extra:
  generator: false
  social:
    - icon: simple/youtube
      link: https://youtube.com/@davidalvarezp
    - icon: simple/twitch
      link: https://twitch.tv/sudodap
    - icon: simple/telegram
      link: https://t.me/sudodap
    - icon: simple/x 
      link: https://x.com/sudodap
    - icon: simple/instagram
      link: https://instagram.com/davidalvarezzp
    - icon: simple/discord
      link: https://discord.gg/x7JFKT2n4X

# Navegación
nav:
 - Homepage: /
 - Inicio: index.md
