authors:

  dap:
    name: David Álvarez Pampillón
    description: >
      SysAdmin y entusiasta de Linux, infraestructura,
      ciberseguridad y automatización.

    avatar: https://github.com/davidalvarezp.png

    url: https://dap.gal/